### ISSUE TITLE
Mastodon認証でエラーが出る

### ISSUE THREAD

**Issue by UTNMY** [tumugin/NowPlayingV2#5]
初めまして、私はなうぷれTunesV2を愛用している者です。

Mastodon認証を試みたところ、認証コードの発行には至りましたが、
認証コードをコピー・アンド・ペーストして「認証してアカウントを
追加する」という水色のボタンをクリックしてもエラーのために認証を
完了できないという問題に直面しました。

**Comment by tumugin** [comment]
@UTNMY さん
Issue報告ありがとうございます。
こちらでpawoo.netのインスタンスを使用して検証してみましたが、正常に認証できているようです。
差し支えなければ、どちらのインスタンスで試されたのか教えていただけないでしょうか？

**Comment by UTNMY** [comment]
私が試したのは、gensokyo.townというインスタンスです。

検証よろしくお願いします。

**Comment by tumugin** [comment]
@UTNMY さん
こちらでgensokyo.townにアカウントを作成し、試しに認証をかけてみたところ認証エラーが発生することが分かりました。
ただ、他のサードパーティ製クライアントでも同様のエラーが発生することと、以下の検証コードでも(他のインスタンスでは発生しない)同様のエラーが発生することから、**恐らくエラーの原因はインスタンス側にあると思われます。**
```ruby
require 'bundler/setup'
Bundler.require(:default)

require 'mastodon'
require 'highline/import'
require 'oauth2'
require 'dotenv'
require 'pp'

DEFAULT_APP_NAME = "mastodon-cli-sample"
DEFAULT_MASTODON_URL = 'https://mstdn.jp'
FULL_ACCESS_SCOPES = "read write follow"

Dotenv.load

if !ENV["MASTODON_URL"]
  ENV["MASTODON_URL"] = ask("Instance URL: "){|q| q.default = DEFAULT_MASTODON_URL}
  File.open(".env", "a+") do |f|
    f.write "MASTODON_URL = '#{ENV["MASTODON_URL"]}'\n"
  end
end

scopes = ENV["MASTODON_SCOPES"] || FULL_ACCESS_SCOPES
app_name = ENV["MASTODON_APP_NAME"] || DEFAULT_APP_NAME

if !ENV["MASTODON_CLIENT_ID"] || !ENV["MASTODON_CLIENT_SECRET"]
  client = Mastodon::REST::Client.new(base_url: ENV["MASTODON_URL"])
  app = client.create_app(app_name, "urn:ietf:wg:oauth:2.0:oob", scopes)
  ENV["MASTODON_CLIENT_ID"] = app.client_id
  ENV["MASTODON_CLIENT_SECRET"] = app.client_secret
  File.open(".env", "a+") do |f|
    f.write "MASTODON_CLIENT_ID = '#{ENV["MASTODON_CLIENT_ID"]}'\n"
    f.write "MASTODON_CLIENT_SECRET = '#{ENV["MASTODON_CLIENT_SECRET"]}'\n"
  end
end

if !ENV["MASTODON_ACCESS_TOKEN"]
  client = OAuth2::Client.new(ENV["MASTODON_CLIENT_ID"],
                              ENV["MASTODON_CLIENT_SECRET"],
                              site: ENV["MASTODON_URL"])
  print "Open URL below:\n"
  print client.auth_code.authorize_url(redirect_uri: 'urn:ietf:wg:oauth:2.0:oob') + "\n"
  code = ask('Your Code:')
  token = client.auth_code.get_token(code,{redirect_uri:'urn:ietf:wg:oauth:2.0:oob'})
  ENV["MASTODON_ACCESS_TOKEN"] = token.token
  File.open(".env", "a+") do |f|
    f.write "MASTODON_ACCESS_TOKEN = '#{ENV["MASTODON_ACCESS_TOKEN"]}'\n"
  end
end

client = Mastodon::REST::Client.new(base_url: ENV["MASTODON_URL"],
                                    bearer_token: ENV["MASTODON_ACCESS_TOKEN"])

## 投稿する
message = ARGV[0] || ask("Your Message: ")
response = client.create_status(message)
#
### とりあえず結果を出力してみる
pp response
```
```
/home/kazuki/Dev/mastodon_test/vendor/bundler/ruby/2.4.0/gems/oauth2-1.4.0/lib/oauth2/client.rb:119:in `request': invalid_grant: 指定された認証許可は無効であるか、期限切れ、取り消されている、リダイレクトURIの不一致、または別のクライアントに発行されています。 (OAuth2::Error)
{"error":"invalid_grant","error_description":"invalid_grant: 指定された認証許可は無効であるか、期限切れ、取り消されている、リダイレクトURIの不一致、または別のクライアントに発行されています。 "}
        from /home/kazuki/Dev/mastodon_test/vendor/bundler/ruby/2.4.0/gems/oauth2-1.4.0/lib/oauth2/client.rb:146:in `get_token'
        from /home/kazuki/Dev/mastodon_test/vendor/bundler/ruby/2.4.0/gems/oauth2-1.4.0/lib/oauth2/strategy/auth_code.rb:30:in `get_token'
        from test.rb:47:in `<main>'
```

認証コードの入力ではなく、リダイレクトによって認証コードを渡す方法だと成功するようなので、認証方法を変更すれば対応できますが、申し訳ないのですが、現状一つの挙動のおかしいインスタンスの為にコードを変更するのは難しいです。(Pull Requestがあれば検討しますが...)

**Comment by UTNMY** [comment]
@tumugin 様

コメントを確認しました。
さしあたって、管理者に相談するなどの対応をしようかと思います。
検証ありがとうございました。
